trigger:
  - master

variables:
  DisableDockerDetector: true

jobs:
  - job: Docker
    pool:
      vmImage: ubuntu-latest
    steps:
      - bash: |
          az keyvault secret download -n "msint-spn-cert-pem" --vault-name "$(kv.name.pkgRelease)" --file "$(System.ArtifactsDirectory)/msint-spn-cert.pem"
          az login --service-principal --use-cert-sn-issuer --username $(servicePrincipal.clientId) --tenant $(servicePrincipal.tenantId) -p "$(System.ArtifactsDirectory)/msint-spn-cert.pem"
          az acr login -n msint
          rm -f "$(System.ArtifactsDirectory)/msint-spn-cert.pem"
        name: login_msinternal
      - bash: |
          docker pull msint.azurecr.io/linuxrepos/repoclient:latest repoclient
        name: pull_repoclient