trigger: none
pr: none

jobs:
################################################################################
  - job: linux_arm32
################################################################################
    displayName: Linux ARM32 Base Image Publication
    pool:
      name: $(pool.name)
      demands:
        - Agent.OS -equals Linux
        - Agent.OSArchitecture -equals ARM
        - agent-osbits -equals 32
        - run-base-image-release -equals true
        - false

    variables:
      os: linux
      arch: arm32v7

    steps:
    - pwsh: |
        # Get the version from each file location
        # EdgeAgent (azureiotedge-agent-base)
        $pathPrefix = '$(Build.SourcesDirectory)/edge-agent/docker/$(os)/$(arch)'
        $unberlyingFilePath = $pathPrefix + '/base/Dockerfile' | Resolve-path
        $underlyingTag = $($(Get-Content $unberlyingFilePath | Select-String "ARG base_tag=") -split "=")[1]
        $imageFilePath = $pathPrefix + '/Dockerfile' | Resolve-path
        $edgeAgentTag = $($(Get-Content $imageFilePath | Select-String "ARG base_tag=") -split "=")[1]
        Write-Output "azureiotedge-agent-base:$edgeAgentTag <= $underlyingTag"
        Write-Output "##vso[task.setvariable variable=edgeAgentTag]$edgeAgentTag"

        # EdgeHub (azureiotedge-hub-base)
        $pathPrefix = '$(Build.SourcesDirectory)/edge-hub/docker/$(os)/$(arch)'
        $unberlyingFilePath = $pathPrefix + '/base/Dockerfile' | Resolve-path
        $underlyingTag = $($(Get-Content $unberlyingFilePath | Select-String "ARG base_tag=") -split "=")[1]
        $imageFilePath = $pathPrefix + '/Dockerfile' | Resolve-path
        $edgeHubTag = $($(Get-Content $imageFilePath | Select-String "ARG base_tag=") -split "=")[1]
        Write-Output "azureiotedge-hub-base:$edgeHubTag <= $underlyingTag"
        Write-Output "##vso[task.setvariable variable=edgeHubTag]$edgeHubTag"

        # TempSensor (azureiotedge-module-base)
        $pathPrefix = '$(Build.SourcesDirectory)/edge-modules/SimulatedTemperatureSensor/docker/$(os)/$(arch)'
        $unberlyingFilePath = $pathPrefix + '/base/Dockerfile' | Resolve-path
        $underlyingTag = $($(Get-Content $unberlyingFilePath | Select-String "ARG base_tag=") -split "=")[1]
        $imageFilePath = $pathPrefix + '/Dockerfile' | Resolve-path
        $moduleTag = $($(Get-Content $imageFilePath | Select-String "ARG base_tag=") -split "=")[1]
        Write-Output "azureiotedge-module-base:$moduleTag <= $underlyingTag"
        Write-Output "##vso[task.setvariable variable=moduleTag]$moduleTag"

        # Test Analyzer (azureiotedge-module-base-full)
        $pathPrefix = '$(Build.SourcesDirectory)/test/modules/TestAnalyzer/docker/$(os)/$(arch)'
        $unberlyingFilePath = $pathPrefix + '/base/Dockerfile' | Resolve-path
        $underlyingTag = $($(Get-Content $unberlyingFilePath | Select-String "ARG base_tag=") -split "=")[1]
        $imageFilePath = $pathPrefix + '/Dockerfile' | Resolve-path
        $fullModuleTag = $($(Get-Content $imageFilePath | Select-String "ARG base_tag=") -split "=")[1]
        Write-Output "azureiotedge-module-base-full:$fullModuleTag <= $underlyingTag"
        Write-Output "##vso[task.setvariable variable=fullModuleTag]$fullModuleTag"

      displayName: Overview ARM32
      name: overview
    - template: ../e2e/templates/e2e-clean-directory.yaml

################################################################################
  - job: linux_arm64
################################################################################
    displayName: Linux ARM64 Base Image Publication
    pool:
      name: $(pool.name)
      demands:
        - Agent.OS -equals Linux
        - Agent.OSArchitecture -equals ARM64
        - agent-osbits -equals 64
        - run-base-image-release -equals true

    variables:
      os: linux
      arch: arm64v8


    steps:
    - pwsh: |
        # Tuple format: (ModuleRepoPath, BaseImageName, ReturningVstsVar)
        $info = New-Object System.Collections.ArrayList
        $info.AddRange((
          [Tuple]::Create("edge-agent","azureiotedge-agent-base", "edgeAgentTag"),
          [Tuple]::Create("edge-hub","azureiotedge-hub-base", "edgeHubTag"),
          [Tuple]::Create("edge-modules/SimulatedTemperatureSensor","azureiotedge-module-base", "moduleTag"),
          [Tuple]::Create("test/modules/TestAnalyzer","azureiotedge-module-base-full", "fullModuleTag")
          ));
        # Write-Output "##vso[task.setvariable variable=info]$info"
        # echo "Gettype: $($info.GetType())"

        $serialize_info = "$([System.Management.Automation.PSSerializer]::Serialize($info))"
        echo $serialize_info
        Write-Output "##vso[task.setvariable variable=serialize_info]$serialize_info"
      displayName: Get Predefined Info
      name: moduleInfo

    - pwsh: |
        # You can access the info using $(info)
        echo "() = $(info)"
        # echo "Gettype = $($(info).GetType())"

        echo "$(serialize_info)"
        $hopefulString = '$(serialize_info)'
        echo $hopefulString
        #$info =  [System.Management.Automation.PSSerializer]::Deserialize($hopefulString)

        #$moduleInfo = $[info]
        #echo $moduleInfo

        # echo "Gettype: $($(info).GetType())"
        # echo access item1 $(info).Item1
        
        # echo "(info).Item1 = $($(info).Item1)"

        # TODO: Put this on a template
        # Get the version from each file location
        # EdgeAgent (azureiotedge-agent-base)
        # $pathPrefix = '$(Build.SourcesDirectory)/edge-agent/docker/$(os)/$(arch)'
        # $unberlyingFilePath = $pathPrefix + '/base/Dockerfile' | Resolve-path
        # $underlyingTag = $($(Get-Content $unberlyingFilePath | Select-String "ARG base_tag=") -split "=")[1]
        # $imageFilePath = $pathPrefix + '/Dockerfile' | Resolve-path
        # $edgeAgentTag = $($(Get-Content $imageFilePath | Select-String "ARG base_tag=") -split "=")[1]
        # Write-Output "azureiotedge-agent-base:$edgeAgentTag <= $underlyingTag"
        # Write-Output "##vso[task.setvariable variable=edgeAgentTag]$edgeAgentTag"

        # # EdgeHub (azureiotedge-hub-base)
        # $pathPrefix = '$(Build.SourcesDirectory)/edge-hub/docker/$(os)/$(arch)'
        # $unberlyingFilePath = $pathPrefix + '/base/Dockerfile' | Resolve-path
        # $underlyingTag = $($(Get-Content $unberlyingFilePath | Select-String "ARG base_tag=") -split "=")[1]
        # $imageFilePath = $pathPrefix + '/Dockerfile' | Resolve-path
        # $edgeHubTag = $($(Get-Content $imageFilePath | Select-String "ARG base_tag=") -split "=")[1]
        # Write-Output "azureiotedge-hub-base:$edgeHubTag <= $underlyingTag"
        # Write-Output "##vso[task.setvariable variable=edgeHubTag]$edgeHubTag"

        # # TempSensor (azureiotedge-module-base)
        # $pathPrefix = '$(Build.SourcesDirectory)/edge-modules/SimulatedTemperatureSensor/docker/$(os)/$(arch)'
        # $unberlyingFilePath = $pathPrefix + '/base/Dockerfile' | Resolve-path
        # $underlyingTag = $($(Get-Content $unberlyingFilePath | Select-String "ARG base_tag=") -split "=")[1]
        # $imageFilePath = $pathPrefix + '/Dockerfile' | Resolve-path
        # $moduleTag = $($(Get-Content $imageFilePath | Select-String "ARG base_tag=") -split "=")[1]
        # Write-Output "azureiotedge-module-base:$moduleTag <= $underlyingTag"
        # Write-Output "##vso[task.setvariable variable=moduleTag]$moduleTag"

        # # Test Analyzer (azureiotedge-module-base-full)
        # $pathPrefix = '$(Build.SourcesDirectory)/test/modules/TestAnalyzer/docker/$(os)/$(arch)'
        # $unberlyingFilePath = $pathPrefix + '/base/Dockerfile' | Resolve-path
        # $underlyingTag = $($(Get-Content $unberlyingFilePath | Select-String "ARG base_tag=") -split "=")[1]
        # $imageFilePath = $pathPrefix + '/Dockerfile' | Resolve-path
        # $fullModuleTag = $($(Get-Content $imageFilePath | Select-String "ARG base_tag=") -split "=")[1]
        # Write-Output "azureiotedge-module-base-full:$fullModuleTag <= $underlyingTag"
        # Write-Output "##vso[task.setvariable variable=fullModuleTag]$fullModuleTag"
      displayName: Overview ARM64
      name: overview

    # - template: ../e2e/templates/e2e-clean-directory.yaml

    # - pwsh: |
    #     #TODO: Clean up these artifacts
    #     Invoke-WebRequest -Uri $("https://edgebuild.blob.core.windows.net/librocksdb/librocksdb.so." + $arch) -OutFile "$(Build.SourcesDirectory)/librocksdb.so"

    #     #Copy this next to the Dockerfile
    #     # iotedge/edge-agent/docker/linux/arm64v8/base
    #     Copy-Item "$(Build.SourcesDirectory)/librocksdb.so" -Destination "C:\Presentation"

    #      foreach ( $word in ("ab", "cd", "ef") ) { echo $word }
    #   displayName: Download librocksdb.so

