trigger: none
pr: none

variables:
  DisableDockerDetector: true

resources:
  repositories:
  - repository: azure-iotedge
    type: github
    endpoint: azure-iot-edge-iotedge1-github
    name: azure/azure-iotedge
    ref: main

stages:
  - stage: PublishArtifact
    displayName: Publish Artifacts
    jobs:
    - job: downloadArtifacts
      displayName: Release Agent Setup
      strategy:
        matrix:
          Ubuntu1804-amd64:
            pool_name: 'Azure-IoT-Edge-1ES-Hosted-Linux'
            agent_demands: 'ImageOverride -equals agent-aziotedge-ubuntu-20.04-docker'
            os: ubuntu20.04
            arch: amd64
            ext: deb
          # Ubuntu1804-arm64:
          #   pool_name: 'Azure-IoT-Edge-1ES-Hosted-Linux-Arm64'
          #   agent_demands: 'ImageOverride -equals agent-aziotedge-ubuntu-18.04-arm64'
          #   os: ubuntu18.04
          #   arch: arm64
          #   ext: deb
      pool:
        name: $(pool_name)
        demands:
        - $(agent_demands)
      steps:
      - checkout: azure-iotedge
        submodules: recursive
      - checkout: self
      - script: |
            wait-for-dpkg-lock 120

            if ! command -v jq &> /dev/null
            then
                sudo apt-get install jq -y
            fi
        name: SetupTestAgent
        displayName: Setup Test Agent
