[package]
name = "edgelet"
version = "0.1.0"
authors = ["Azure IoT Edge Devs <edgedevs@microsoft.com"]
publish = false

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
url = "1.7"

docker-mri = { path = "../docker-mri" }
edgelet-core = { path = "../edgelet-core" }
clap = "2.31.2"
config = "0.8.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1"
edgelet-http-mgmt = { path = "../edgelet-http-mgmt" }
