[package]
name = "edgelet"
version = "0.1.0"
authors = ["Azure IoT Edge Devs <edgedevs@microsoft.com"]
publish = false

[dependencies]
clap = "2.31.2"
config = "0.8.0"
env_logger = "0.5"
failure = "0.1"
futures = "0.1"
hyper = "0.11"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
url = "1.7"

edgelet-core = { path = "../edgelet-core" }
edgelet-docker = { path = "../edgelet-docker" }
edgelet-http = { path = "../edgelet-http" }
edgelet-http-mgmt = { path = "../edgelet-http-mgmt" }
edgelet-http-workload = { path = "../edgelet-http-workload" }
edgelet-iothub = { path = "../edgelet-iothub" }
iothubservice = { path = "../iothubservice" }
