[package]
name = "provisioning"
version = "0.1.0"
authors = ["Janice D'Sa <jadsa@microsoft.com>"]

[dependencies]
base64 = "0.9"
bytes = "0.4"
failure = "0.1"
futures = "0.1"
log = "0.4"
regex = "0.2"
hyper = "0.11"
url = "1.7"

hsm = { path = "../hsm-rs"}
dps = { path = "../dps" }
edgelet-core = { path = "../edgelet-core" }
edgelet-hsm = { path = "../edgelet-hsm" }
edgelet-http = { path = "../edgelet-http" }
edgelet-utils = { path = "../edgelet-utils" }

[dev_dependencies]
tokio-core = "0.1"
