[package]
name = "edgelet-http"
version = "0.1.0"
authors = ["Azure IoT Edge Devs <edgedevs@microsoft.com"]
publish = false

[dependencies]
chrono = "0.4"
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
hyper = "0.11"
log = "0.4"
regex = "0.2"
serde_json = "1.0"
url = "1.7"
