[package]
name = "iotedge"
version = "0.1.0"
authors = ["Azure IoT Edge Devs <edgedevs@microsoft.com>"]

[dependencies]
clap = "2.31"
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"

edgelet-core = { path = "../edgelet-core" }
edgelet-http-mgmt = { path = "../edgelet-http-mgmt" }
management = { path = "../management" }
