[workspace]
members = [
    "docker-mri",
    "docker-rs",
    "edgelet",
    "edgelet-core",
    "edgelet-grpc",
    "edgelet-http",
    "edgelet-utils",
    "edgelet-test-utils",
    "iothubservice-rs",
    "hsm-rs",
    "hsm-sys",
]
