[workspace]
members = [
    "docker-rs",
    "edgelet-core",
    "edgelet-docker",
    "edgelet-hsm",
    "edgelet-http",
    "edgelet-http-mgmt",
    "edgelet-http-workload",
    "edgelet-iothub",
    "edgelet-utils",
    "edgelet-test-utils",
    "iotedged",
    "iotedge",
    "iothubservice",
    "hsm-rs",
    "hsm-sys",
    "management",
    "tokio-named-pipes",
]
