[package]
name = "docker-rs"
version = "0.1.0"
authors = ["Azure IoT Edge Devs <edgedevs@microsoft.com"]
publish = false

[dependencies]
base64 = "0.9.0"
failure = "0.1"
futures = "0.1"
hyper = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
url = "1.5"

[dev-dependencies]
tokio-core = "*"
