provisioning:
  source: "manual"
  device_connection_string: "HostName=something.some.com;DeviceId=some;SharedAccessKey=some"

agent:
  name: "edgeAgent"
  type: "docker"
  env": {}
  config:
    image: "mcr.microsoft.com/azureiotedge-agent:1.0"
    auth: {}

hostname: "localhost"

connect:
  management_uri: "http://localhost:15580"
  workload_uri: "http://localhost:15581"

listen:
  management_uri: "http://0.0.0.0:15580"
  workload_uri: "http://0.0.0.0:15581"

homedir: "C:\\Temp\\iotedge"

moby_runtime:
  uri: "npipe://./pipe/docker_engine"
  network: "nat"
