[package]
name = "edgelet-core"
version = "0.1.0"
authors = ["Azure IoT Edge Devs <edgedevs@microsoft.com"]
publish = false

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
futures = "0.1"
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
