trigger: none
pr: none

variables:
  DisableDockerDetector: true

resources:
  repositories:
  - repository: azure-iotedge
    type: github
    endpoint: azure-iot-edge-iotedge1-github
    name: azure/azure-iotedge
    ref: main

stages:
  - stage: RunSmokeTest
    displayName: Smoke Test
    jobs:
    - job: linux
      displayName: Linux
      strategy:
        matrix:
          Centos75-amd64:
            os: centos7
            artifactName: iotedged-centos7-amd64
            identityServiceArtifactName: packages_centos-7_amd64
            identityServicePackageFilter: aziot-identity-service-*.x86_64.rpm
          RedHat8-amd64:
            os: redhat8
            artifactName: iotedged-redhat8-amd64
            identityServiceArtifactName: packages_redhat-ubi8-latest_amd64
            identityServicePackageFilter: aziot-identity-service-*.x86_64.rpm
      steps:
        - task: AzureKeyVault@1
          displayName: Get secrets
          inputs:
            azureSubscription: 'azureiotedge-arm'
            keyVaultName: 'edgebuildkv'
            secretsFilter: >-
              GitHubAccessToken
        - checkout: self
        - task: DownloadPipelineArtifact@2
          displayName: Download Pipeline Build Packages
          inputs:
            source: 'current'
            path: $(System.ArtifactsDirectory)
            patterns: |
                $(artifactName)/*.deb
                $(artifactName)/*.rpm
        - task: PowerShell@2
          displayName: 'Download aziot-identity-service'
          inputs:
            filePath: $(Build.SourcesDirectory)/scripts/local/test/DownloadIdentityService.ps1
            workingDirectory: $(Build.SourcesDirectory)
          env:
            GITHUB_TOKEN: $(GitHubAccessToken)
            ARTIFACT_NAME: $(identityServiceArtifactName)
            PACKAGE_FILTER: $(identityServicePackageFilter)
            DOWNLOAD_PATH: $(System.ArtifactsDirectory)/$(artifactName)
            IDENTITY_SERVICE_COMMIT: $(aziotis.commit)

    - job: downloadArtifacts
      displayName: Release Artifact Smoke Tests
      strategy:
        matrix:
          # Debian11-armhf:
          #   pool_name: 'Azure-IoT-Edge-Core'
          #   agent_demands: 'deb11-e2e-tests -equals true'
          #   os: debian11
          #   arch: armhf
          #   ext: deb

          Ubuntu1804-amd64:
            pool_name: 'Azure-IoT-Edge-1ES-Hosted-Linux'
            agent_demands: 'ImageOverride -equals agent-aziotedge-ubuntu-18.04-docker'
            os: ubuntu18.04
            arch: amd64
            ext: deb
          Ubuntu1804-arm64:
            pool_name: 'Azure-IoT-Edge-1ES-Hosted-Linux-Arm64'
            agent_demands: 'ImageOverride -equals agent-aziotedge-ubuntu-18.04-arm64'
            os: ubuntu18.04
            arch: arm64
            ext: deb
          
          Ubuntu2004-amd64:
            pool_name: 'Azure-IoT-Edge-1ES-Hosted-Linux'
            agent_demands: 'ImageOverride -equals agent-aziotedge-ubuntu-20.04-docker'
            os: ubuntu20.04
            arch: amd64
            ext: deb
          Ubuntu2004-arm64:
            pool_name: 'Azure-IoT-Edge-1ES-Hosted-Linux-Arm64'
            agent_demands: 'ImageOverride -equals agent-aziotedge-ubuntu-20.04-arm64'
            os: ubuntu20.04
            arch: arm64
            ext: deb
      pool:
        name: $(pool_name)
        demands:
        - $(agent_demands)

      steps:
      - checkout: azure-iotedge
        submodules: recursive
      - checkout: self
      - task: Bash@3
        displayName: Setup Test Agent
        condition: true
        name: SetupTestAgent
        # BEARWASHERE -- "edgeletVersion" needs to be a pipeline variable
        inputs:
          targetType: 'inline'
          script: |
            # Source the scripts & Update version files
            sudo chmod +x $(Build.SourcesDirectory)/iotedge/scripts/linux/smokeTestHelper.sh
            source $(Build.SourcesDirectory)/iotedge/scripts/linux/smokeTestHelper.sh

            wait-for-dpkg-lock 120

            if [[ "$(arch)" == "arm"* ]]; then
              sudo apt-get install jq -y
            fi

      - task: Bash@3
        displayName: Get Parameters From Azure-iotedge
        condition: true
        name: GitHubParameters
        inputs:
          targetType: 'inline'
          script: |
            # Source the scripts and get versions
            edgeletVersion=$(cat $(Build.SourcesDirectory)/azure-iotedge/latest-aziot-edge.json | jq ".\"aziot-edge\"" | tr -d '"')
            iisVersion=$(cat cat $(Build.SourcesDirectory)/azure-iotedge/latest-aziot-identity-service.json | jq ".\"aziot-identity-service\"" | tr -d '"')

            echo "##vso[task.setvariable variable=edgeletVersion;isOutput=true]$edgeletVersion"
            echo "##vso[task.setvariable variable=iisVersion;isOutput=true]$iisVersion"
        env:
          GITHUB_PAT: "$(GitHubAccessToken)"
      - task: Bash@3
        displayName: Download Edgelet GitHub
        condition: true
        inputs:
          targetType: 'inline'
          script: |
            edgeletVersion=$(GitHubParameters.edgeletVersion)
            iisVersion=$(GitHubParameters.iisVersion)

            wget https://github.com/Azure/azure-iotedge/releases/download/$edgeletVersion/aziot-edge_$edgeletVersion-1_$(os)_$(arch).$(ext) -O $(System.ArtifactsDirectory)/aziot-edge_$edgeletVersion-1_$(os)_$(arch)_github.$(ext)
            wget https://github.com/Azure/azure-iotedge/releases/download/$edgeletVersion/aziot-identity-service_$iisVersion-1_$(os)_$(arch).$(ext) -O $(System.ArtifactsDirectory)/aziot-identity-service_$iisVersion-1_$(os)_$(arch)_github.$(ext)

      - task: Bash@3
        displayName: Released Artifacts Smoke Tests
        condition: true
        inputs:
          targetType: 'inline'
          script: |
            # Source the scripts & Update version files
            sudo chmod +x $(Build.SourcesDirectory)/iotedge/scripts/linux/smokeTestHelper.sh
            source $(Build.SourcesDirectory)/iotedge/scripts/linux/smokeTestHelper.sh

            if [[ "$(os)" == "ubuntu"* ]]; then
            # Ubuntu
              if [[ "$(os)" == *"20.04" ]]; then
                setup-focal-source-apt
                setup-config-apt "https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb"
              elif [[ "$(os)" == *"18.04" ]]; then
                setup-config-apt "https://packages.microsoft.com/config/ubuntu/18.04/multiarch/packages-microsoft-prod.deb"
              else
                echo "Unsupported OS: $(os)"
                exit 1;
              fi
            elif [[ "$(os)" == "debian11" ]]; then
              # Debian
              echo "Setup source artifact repository"
              curl https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb > ./packages-microsoft-prod.deb
              sudo apt install ./packages-microsoft-prod.deb
              sudo apt-get update
            else
              echo "Unsupported OS: $(os)"
              exit 1;
            fi

            echo $'\n\n================================================\n\n'
            echo "Aziot-edge"
            test-released-metadata "aziot-edge" "$(GitHubParameters.edgeletVersion)"

            test-released-artifact \
              "aziot-edge" \
              "$(GitHubParameters.edgeletVersion)" \
              "$(System.ArtifactsDirectory)" \
              "$(GitHubParameters.edgeletVersion)-1_$(os)_$(arch)_github.$(ext)" \
              "$(edgelet.maxPercentAllowed)" \
              "$(IsCheckPreviousPkg)"

            echo $'\n\n================================================\n\n'
            echo "Aziot-identity-service"
            test-released-metadata "aziot-identity-service" "$(GitHubParameters.iisVersion)"

            test-released-artifact \
              "aziot-identity-service" \
              "$(GitHubParameters.iisVersion)" \
              "$(System.ArtifactsDirectory)" \
              "$(GitHubParameters.iisVersion)-1_$(os)_$(arch)_github.$(ext)" \
              "$(edgelet.maxPercentAllowed)" \
              "$(IsCheckPreviousPkg)"

      - task: Bash@3
        displayName: Released Images Smoke Tests
        condition: true
        inputs:
          targetType: 'inline'
          script: |
            # Source the scripts & Update version files
            sudo chmod +x $(Build.SourcesDirectory)/iotedge/scripts/linux/smokeTestHelper.sh
            source $(Build.SourcesDirectory)/iotedge/scripts/linux/smokeTestHelper.sh
