[package]
name = "edgelet-http-workload"
version = "0.1.0"
authors = ["Azure IoT Edge Devs <edgedevs@microsoft.com"]
publish = false

[dependencies]
base64 = "0.9.0"
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
hyper = "0.11"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

edgelet-core = { path = "../edgelet-core" }
edgelet-http = { path = "../edgelet-http" }
workload = { path = "../workload" }

[dev-dependencies]
chrono = { version = "0.4", features = ["serde"] }
