[package]
name = "edgelet-test-utils"
version = "0.1.0"
authors = ["Azure IoT Edge Devs <edgedevs@microsoft.com"]
publish = false

[dependencies]
futures = "0.1"
hyper = "0.11"
serde = "1"
serde_json = "1"
tokio-io = "0.1"
