[package]
name = "edgelet-test-utils"
version = "0.1.0"
authors = ["Azure IoT Edge Devs <edgedevs@microsoft.com>"]
publish = false

[dependencies]
failure = "0.1"
futures = "0.1"
hyper = "0.11"
serde = "1"
serde_derive = "1"
serde_json = "1"
tokio-io = "0.1"

edgelet-core = { path = "../edgelet-core" }

[target.'cfg(unix)'.dependencies]
hyperlocal = "0.4"

[target.'cfg(windows)'.dependencies]
httparse = "1.2"
mio = "0.6"
mio-named-pipes = "0.1"