provisioning:
  source: "manual"
  device_connection_string: "HostName=something.some.com;DeviceId=some;SharedAccessKey=some"

agent:
  name: "edgeAgent"
  type: "docker"
  env": {}
  config:
    image: "mcr.microsoft.com/azureiotedge-agent:1.0"
    auth: {}

hostname: "localhost"

connect:
  management_uri: "unix:///var/run/iotedge/mgmt.sock"
  workload_uri: "unix:///var/run/iotedge/workload.sock"

listen:
  management_uri: "unix:///var/run/iotedge/mgmt.sock"
  workload_uri: "unix:///var/run/iotedge/workload.sock"

homedir: "/tmp/iotedge"

moby_runtime:
  uri: "unix:///var/run/docker.sock"
  network: "azure-iot-edge"
