provisioning:
  source: "manual"
  device_connection_string: "HostName=something.some.com;DeviceId=some;SharedAccessKey=some"

agent:
  name: "edgeAgent"
  type: "docker"
  env": {}
  config:
    image: "microsoft/azureiotedge-agent:1.0"
    auth: {}

hostname: "localhost"

connect:
  workload_uri: "http://localhost:8081"
  management_uri: "http://localhost:8080"

listen:
  workload_uri: "http://0.0.0.0:8081"
  management_uri: "http://0.0.0.0:8080"

homedir: "/tmp/iotedge"

moby_runtime:
  uri: "unix:///var/run/docker.sock"
  network: "azure-iot-edge"
