[package]
name = "iothubservice"
version = "0.1.0"
authors = ["Azure IoT Edge Devs <edgedevs@microsoft.com"]
publish = false

[dependencies]
failure = "0.1"
futures = "0.1"
hyper = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.7"

edgelet-utils = { path = "../edgelet-utils" }

[dev_dependencies]
tokio-core = "0.1"
